package mapeo_tienda;
// Generated 11/10/2019 09:29:33 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private int idMarca;
     private String descripccion;
     private Set productos = new HashSet(0);

    public Marca() {
    }

	
    public Marca(int idMarca, String descripccion) {
        this.idMarca = idMarca;
        this.descripccion = descripccion;
    }
    public Marca(int idMarca, String descripccion, Set productos) {
       this.idMarca = idMarca;
       this.descripccion = descripccion;
       this.productos = productos;
    }
   
    public int getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(int idMarca) {
        this.idMarca = idMarca;
    }
    public String getDescripccion() {
        return this.descripccion;
    }
    
    public void setDescripccion(String descripccion) {
        this.descripccion = descripccion;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


