package mapeo_tienda;
// Generated 11/10/2019 09:29:33 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Presentacion generated by hbm2java
 */
public class Presentacion  implements java.io.Serializable {


     private int idPresentacion;
     private String descripccion;
     private Set productos = new HashSet(0);

    public Presentacion() {
    }

	
    public Presentacion(int idPresentacion, String descripccion) {
        this.idPresentacion = idPresentacion;
        this.descripccion = descripccion;
    }
    public Presentacion(int idPresentacion, String descripccion, Set productos) {
       this.idPresentacion = idPresentacion;
       this.descripccion = descripccion;
       this.productos = productos;
    }
   
    public int getIdPresentacion() {
        return this.idPresentacion;
    }
    
    public void setIdPresentacion(int idPresentacion) {
        this.idPresentacion = idPresentacion;
    }
    public String getDescripccion() {
        return this.descripccion;
    }
    
    public void setDescripccion(String descripccion) {
        this.descripccion = descripccion;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


