package mapeo_tienda;
// Generated 11/10/2019 09:29:33 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Zona generated by hbm2java
 */
public class Zona  implements java.io.Serializable {


     private int idZona;
     private String descripccion;
     private Set productos = new HashSet(0);

    public Zona() {
    }

	
    public Zona(int idZona, String descripccion) {
        this.idZona = idZona;
        this.descripccion = descripccion;
    }
    public Zona(int idZona, String descripccion, Set productos) {
       this.idZona = idZona;
       this.descripccion = descripccion;
       this.productos = productos;
    }
   
    public int getIdZona() {
        return this.idZona;
    }
    
    public void setIdZona(int idZona) {
        this.idZona = idZona;
    }
    public String getDescripccion() {
        return this.descripccion;
    }
    
    public void setDescripccion(String descripccion) {
        this.descripccion = descripccion;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


